In [3]:
import numpy as np

# Diferentes dimensiones

In [6]:
scalar = np.array(52)
scalar
scalar.ndim

0

In [10]:
vector = np.array(range(11))
vector
vector.ndim

1

In [15]:
matriz = np.array([ [1, 2, 3], [4, 5, 6] ])
matriz
matriz.ndim

2

In [21]:
tensor = np.array([[ [1, 2, 3], [4, 5, 6] ],[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
tensor
tensor.ndim

3

# Agregar dimensiones

In [23]:
vector = np.array(range(11),ndmin=3)
print(vector)
vector.ndim

[[[ 0  1  2  3  4  5  6  7  8  9 10]]]


3

In [26]:
expand = np.expand_dims(np.array(range(11)), axis= 0)
print(expand)
expand.ndim

[[ 0  1  2  3  4  5  6  7  8  9 10]]


2

# Quitar dimensiones

In [27]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[ 0  1  2  3  4  5  6  7  8  9 10]]] 3
[ 0  1  2  3  4  5  6  7  8  9 10] 1
