In [2]:
# Importamos nuestra librería
import numpy as np

In [3]:
# Creamos una lista de Python para ejemplificar
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
# Creamos un array de Numpy y comprobamos
array = np.array(lista)
type(array)

numpy.ndarray

In [8]:
# Creamos un array de dos dimenciones(matriz)
matriz = [
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]
]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Indexado, obvio desde 0 hasta n
array[3]
array[4] + array[3]

9

In [16]:
# Indexado de matrices
# Nos trae la primer fila completa
matriz[0]
# Nos trae un elemento específico
matriz[0,0]

1

In [19]:
# El slicing funciona normalmente como con una lista de Python
array[0:4]
# Recordar que el inicio se incluye y el final es excluido
array[3:8]

array([4, 5, 6, 7, 8])

In [23]:
# Slicing con matrices
matriz[1:]
# Slicing de filas y columnas
matriz[1:,:2]

array([[4, 5],
       [7, 8]])

In [65]:
# Matriz de 3 dimensiones
matriz3d = [
            [
             [1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]
            ],
            [
             [13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]
            ],
            [
             [25, 26, 27, 28],
             [29, 30, 31, 32],
             [33, 34, 35, 36]
            ]
]
matriz3d[1:3][0:3]

[[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
 [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]]]